SET(RobartsVTK_GIT_REPOSITORY "git.imaging.robarts.ca/RobartsVTK.git")
SET(RobartsVTK_GIT_TAG "88b61f90e09f26f6cc285ec6bbd9a515fd92f9ba")

SET (RobartsVTK_DIR ${CMAKE_BINARY_DIR}/RobartsVTK CACHE INTERNAL "Path to store RobartsVTK contents.")
ExternalProject_Add(RobartsVTK
SOURCE_DIR "${RobartsVTK_DIR}"
BINARY_DIR "RobartsVTK-bin"
#--Download step--------------
GIT_REPOSITORY "${RobartsVTK_GIT_PROTOCOL}://${RobartsVTK_GIT_REPOSITORY}"
GIT_TAG ${RobartsVTK_GIT_TAG}
#--Configure step-------------
CMAKE_ARGS
  ${ep_common_args}
  -DVTK_DIR:PATH=${VTK_DIR}
  -DITK_DIR:PATH=${ITK_DIR}
  -DBUILD_DOCUMENTATION:BOOL=${RobartsVTK_DOCUMENTATION}
  -DBUILD_SHARED_LIBS:BOOL=${RobartsVTK_BUILD_SHARED_LIBS}
  -DBUILD_TESTING:BOOL=${RobartsVTK_BUILD_TESTING}
  -DRobartsVTK_BUILD_EXAMPLES=${RobartsVTK_BUILD_EXAMPLES}
  -DRobartsVTK_USE_CUDA=${RobartsVTK_USE_CUDA}
  -DCUDA_HOST_COMPILER=${CUDA_HOST_COMPILER}
  -DCUDA_SDK_ROOT_DIR=${CUDA_SDK_ROOT_DIR}
  -DCUDA_TOOLKIT_ROOT_DIR=${CUDA_TOOLKIT_ROOT_DIR}
  -DRobartsVTK_USE_CUDA_VISUALIZATION=${RobartsVTK_USE_CUDA_VISUALIZATION}
  -DRobartsVTK_USE_CUDA_ANALYTICS=${RobartsVTK_USE_CUDA_ANALYTICS}
  -DRobartsVTK_USE_ITK=${RobartsVTK_USE_ITK}
  -DRobartsVTK_USE_LIBXML2=${RobartsVTK_USE_LIBXML2}
  -DRobartsVTK_USE_MWIERZ=${RobartsVTK_USE_MWIERZ}
  -DRobartsVTK_USE_QT=${RobartsVTK_USE_QT}
  -DQT_QMAKE_EXECUTABLE:FILEPATH=${QT_QMAKE_EXECUTABLE}
  -DDESIRED_QT_VERSION=${DESIRED_QT_VERSION}
  -DRobartsVTK_USE_ROBARSTUTILITIES=${RobartsVTK_USE_ROBARSTUTILITIES}
  -DCMAKE_CXX_FLAGS:STRING=${ep_common_cxx_flags}
  -DCMAKE_C_FLAGS:STRING=${ep_common_c_flags}
  -DROBARTSVTK_EXECUTABLE_OUTPUT_PATH:STRING=${RobartsVTK_EXECUTABLE_OUTPUT_PATH}

#--Build step-----------------
#--Install step---------------
INSTALL_COMMAND ""
DEPENDS ${RobartsVTK_DEPENDENCIES}
)

SET(RobartsVTK_DIR ${CMAKE_BINARY_DIR}/RobartsVTK-bin CACHE PATH "The directory containing RobartsVTK binaries" FORCE)
